services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
    volumes:
      - minecraft-volume:/data

  minio:
    container_name: minio
    image: minio/minio
    tty: true
    command: [ "server", "/data", "--console-address", ":9001" ]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - "minio-volume:/data"

  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add myminio http://minio:9000 minio password && /usr/bin/mc ls myminio; do echo 'waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/minecraft-world-data-bucket;
      /usr/bin/mc policy set download myminio/minecraft-world-data-bucket;
      exit 0;
      "

volumes:
  minecraft-volume:
  minio-volume:
